name = "FastHankelTransform"
uuid = "3a9aa71a-4826-43c7-bf6d-7fc63822c18e"
authors = ["Paul Beckman <paul.beckman@cims.nyu.edu>"]
version = "0.1.1"

[deps]
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
FINUFFT = "d8beea63-0952-562e-9c6a-8e8ef7364055"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.6"
Bessels = "0.2.8"
FINUFFT = "3.0.0"
